packages:
  - apps/*
  - packages/*

catalogs:
  default:
    "@eslint/js": ^9.39.1
    "@tailwindcss/vite": ^4.1.17
    "@types/express": ^5.0.5
    "@types/node": 24.10.0
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    "@types/uuid": ^11.0.0
    "@vitejs/plugin-react-swc": ^4.2.1
    citty: ^0.1.6
    concurrently: ^9.2.1
    dotenv: ^17.2.3
    esbuild: ^0.25.12
    eslint: ^9.39.1
    eslint-config-prettier: ^10.1.8
    eslint-plugin-prettier: ^5.5.4
    eslint-plugin-react-hooks: ^7.0.1
    eslint-plugin-react-refresh: ^0.4.24
    express: ^5.1.0
    globals: ^16.5.0
    lucide-react: ^0.552.0
    nx: ^22.0.2
    prettier: ^3.6.2
    react: ^19.2.0
    react-dom: ^19.2.0
    tailwindcss: ^4.1.17
    tsup: 8.5.1
    tsx: ^4.20.6
    typescript: ~5.9.3
    typescript-eslint: ^8.46.3
    uuid: 13.0.0
    vite: ^7.2.4

settings:
  catalogMode: strict
